### ISSUE TITLE
Bug with the logs

### ISSUE THREAD

**Issue by zokiopp** [tera-toolbox/tera-toolbox#23] opened 2019-08-04 23:10 UTC
![BUG](https://user-images.githubusercontent.com/49364142/62430506-c0e9e780-b71d-11e9-99af-f74ccb6631a9.PNG)
I get this after/before Disconnecting of the client. I also think my clients are disconnecting coz of this bug. Whats the cause?

**Comment by caali-hackerman** [comment] 2019-08-15 12:49
For reference: this issue is unrelated to Toolbox, it belongs here: https://github.com/caali-hackerman/data-logger

It's caused _by your disconnects_, not vice versa. Seems to be some weird race condition caused by your dcs. Will be fixed in the next version of the logger, however as I said it's not causing any disconnects whatsoever.

**Closed by caali-hackerman** 2019-08-15 12:49 UTC
